version: "3.9"

networks:
  myNetwork:

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - myNetwork

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - myNetwork

  backend:
    build:
      context: ./backend
    image: backend-image
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - myNetwork
